/** Central plain-English glossary — one source of truth for jargon tooltips. */
export const GLOSSARY: Record<string, string> = {
  TCS: "Tax Collected at Source — tax taken upfront when you send money abroad. You get it back later via your tax return, but it's locked up in the meantime.",
  LRS: "Liberalised Remittance Scheme — the RBI rule that lets each Indian send up to $250,000 abroad per year.",
  STCG: "Short-Term Capital Gain — profit on something held for a short time (≤24 months for foreign assets), taxed at your income-slab rate.",
  LTCG: "Long-Term Capital Gain — profit on something held longer (>24 months for foreign assets); taxed at a lower flat 12.5%.",
  STCL: "Short-Term Capital Loss — a loss on a short-held asset; the most useful kind because it can cancel both short- and long-term gains.",
  LTCL: "Long-Term Capital Loss — a loss on a long-held asset; can only cancel long-term gains.",
  surcharge: "An extra slice of tax for high incomes. On capital gains it's capped at 15%.",
  cess: "A flat 4% Health & Education charge added on top of your tax.",
  "730-day": "The 2-year (730-day) mark. Hold a foreign asset past it and your profit is taxed at the lower long-term rate.",
  DTAA: "Double Taxation Avoidance Agreement — the treaty that stops the same income being fully taxed in both India and another country.",
  FTC: "Foreign Tax Credit — lets you subtract tax already paid abroad from your Indian tax, so you're not taxed twice.",
  "Form 67": "The form you must file to claim your Foreign Tax Credit — do it before you file your return.",
  WHT: "Withholding Tax — tax a country holds back from your dividend before it ever reaches you (the US holds 25% from Indian investors).",
  "estate tax": "A US tax of up to 40% on US assets you leave behind, above a small $60,000 cushion — it applies to foreign investors holding US stocks directly.",
  "US-situs": "An asset legally treated as 'located in' the US — like US company shares — and therefore inside the US estate-tax net.",
  NRA: "Non-Resident Alien — how the US sees an Indian investor; it means a tiny $60,000 estate-tax exemption instead of the large US-citizen one.",
  NRI: "Non-Resident Indian — an Indian citizen who lives abroad and is taxed in India only on Indian income.",
  RNOR: "Resident but Not Ordinarily Resident — a temporary 'golden window' (often after returning to India) where foreign income stays tax-free in India.",
  ROR: "Resident & Ordinarily Resident — fully taxed in India on worldwide income, and must declare all foreign assets.",
  "Section 6": "The Income Tax Act rule that decides — by counting your days in India — whether you're NRI, RNOR or resident.",
  TER: "Total Expense Ratio — the yearly % a fund quietly charges you, whether it goes up or down.",
  brokerage: "The fee your broker charges each time you buy or sell.",
  spread: "The hidden gap between the buy and sell price — a cost you pay even when there's no visible fee.",
  "net returns": "What you actually keep after every tax and fee — the only number that really matters.",
  IFSC: "International Financial Services Centre — the GIFT City zone where investing gets special tax treatment.",
  "Schedule FA": "The part of your tax return where you must list every foreign asset you own — missing it risks a ₹10 lakh penalty.",
};
